### ISSUE TITLE
git.exc.InvalidGitRepositoryError

### ISSUE THREAD

**Issue by akre54** [jheddings/notional#34]
### Description ###

Hi there - I'm getting an `git.exc.InvalidGitRepositoryError` when importing notional. I just installed it via pip.

### Steps To Reproduce ###

```bash
> pip install notional

> python3

>>> import notional
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/notional/__init__.py", line 6, in <module>
    from .version import __version__
  File "/usr/local/lib/python3.9/site-packages/notional/version.py", line 22, in <module>
    repo = git.Repo(basedir, search_parent_directories=True)
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 220, in __init__
    self.working_dir = self._working_tree_dir or self.common_dir  # type: Optional[PathLike]
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 303, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError

```

**Comment by jheddings** [comment]
Apologies for that!  The logic for version number lookup was breaking since you are using `gitpython` in another project...  I have improved the version lookup and you should be able to install it now.

**Comment by akre54** [comment]
Thank you!
